---
apiVersion: external-secrets.io/v1alpha1
kind: ClusterSecretStore
metadata:
  name: openbao-backend
  labels:
    app.kubernetes.io/name: clustersecretstore
    app.kubernetes.io/part-of: external-secrets
    app.kubernetes.io/managed-by: argocd
spec:
  provider:
    vault:
      server: "http://openbao.vault.svc.cluster.local:8200"
      path: "secret"
      version: "v2"
      auth:
        kubernetes:
          mountPath: "kubernetes"
          role: "external-secrets"
          serviceAccountRef:
            name: external-secrets
            namespace: external-secrets
