---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: test-openbao-secret
  namespace: external-secrets
  labels:
    app.kubernetes.io/name: external-secret
    app.kubernetes.io/part-of: external-secrets
    app.kubernetes.io/managed-by: argocd
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: openbao-backend
  target:
    name: test-db-credentials
    creationPolicy: Owner
  data:
    - secretKey: username
      remoteRef:
        key: secret/data/test/db
        property: username
    - secretKey: password
      remoteRef:
        key: secret/data/test/db
        property: password
