apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: web-filesystem

resources:
  - namespace.yaml
  - serviceaccount.yaml
  - configmap.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml
  - networkpolicy.yaml
  - limitrange.yaml
  - resourcequota.yaml

commonLabels:
  app.kubernetes.io/name: web-filesystem
  app.kubernetes.io/part-of: agent-filesystem

images:
  - name: web-filesystem
    newTag: "0.1.0"
