apiVersion: v1
kind: Namespace
metadata:
  name: web-filesystem
  labels:
    app.kubernetes.io/name: web-filesystem
    app.kubernetes.io/part-of: agent-filesystem
    environment: local
    pod-security.kubernetes.io/enforce: privileged
    pod-security.kubernetes.io/audit: privileged
    pod-security.kubernetes.io/warn: privileged
