apiVersion: v1
kind: Service
metadata:
  name: web-filesystem
  namespace: web-filesystem
  labels:
    app.kubernetes.io/name: web-filesystem
    app.kubernetes.io/part-of: agent-filesystem
    app.kubernetes.io/component: server
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: web-filesystem
    app.kubernetes.io/component: server
  ports:
    - name: http
      port: 80
      targetPort: http
      protocol: TCP
