apiVersion: v1
kind: ServiceAccount
metadata:
  name: web-filesystem
  namespace: web-filesystem
  labels:
    app.kubernetes.io/name: web-filesystem
    app.kubernetes.io/part-of: agent-filesystem
automountServiceAccountToken: false
