apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: traefik
  namespace: kube-system
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: traefik
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: headlamp
  namespace: headlamp
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: headlamp
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: web-filesystem
  namespace: web-filesystem
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: web-filesystem
      app.kubernetes.io/component: server
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: grafana
  namespace: observability
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: grafana
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: victoria-metrics
  namespace: observability
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/component: server
      app.kubernetes.io/instance: victoria-metrics
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: victoria-logs
  namespace: observability
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/component: server
      app.kubernetes.io/instance: victoria-logs
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: keycloak
  namespace: iam
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: keycloak
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: openbao
  namespace: vault
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: openbao
