apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: keycloak
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    - repoURL: https://codecentric.github.io/helm-charts
      chart: keycloakx
      targetRevision: "*"
      helm:
        releaseName: keycloak
        valueFiles:
          - $values/apps/keycloak/values.yaml
    - repoURL: https://github.com/kurtyoon/k8s-play-ground.git
      targetRevision: main
      ref: values
    - repoURL: https://github.com/kurtyoon/k8s-play-ground.git
      targetRevision: main
      path: apps/keycloak/postgres
  destination:
    server: https://kubernetes.default.svc
    namespace: iam
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
